Repository Likelion-Kwangwoon/notodo, pull requests merged in 2023-05, with the labels that each got.

#20 변경 디자인 수정 및 에셋 세팅
  notodo/public/index.html
  notodo/src/assets/CharList.js
  notodo/src/assets/char-green.svg
  notodo/src/assets/char-red.svg
  notodo/src/assets/char-yellow.svg
  notodo/src/assets/icon-back.svg
  notodo/src/assets/icon-bell.svg
  notodo/src/assets/icon-bell_on.svg
  notodo/src/assets/icon-calendar.svg
  notodo/src/assets/icon-close.svg
  notodo/src/assets/icon-desc.svg
  notodo/src/assets/icon-down-gray.svg
  notodo/src/assets/icon-down-red.svg
  notodo/src/assets/icon-fail-fill.svg
  notodo/src/assets/icon-fail.svg
  notodo/src/assets/icon-heart-fill.svg
  notodo/src/assets/icon-heart.svg
  notodo/src/assets/icon-home-fill.svg
  notodo/src/assets/icon-home.svg
  notodo/src/assets/icon-plus.svg
  notodo/src/assets/icon-profile-fill.svg
  notodo/src/assets/icon-profile.svg
  notodo/src/assets/icon-search-fill.svg
  notodo/src/assets/icon-search.svg
  notodo/src/assets/icon-share.svg
  notodo/src/assets/icon-suc-fill.svg
  notodo/src/assets/icon-suc.svg
  notodo/src/assets/icon-up-gray.svg
  notodo/src/assets/icon-up-green.svg
  notodo/src/assets/logo.svg
  notodo/src/components/MonthState/index.jsx
  notodo/src/components/MonthState/style.js
  notodo/src/components/UserInfo/style.js
  notodo/src/components/WeekPicker/style.js
  notodo/src/components/calendar/index.jsx
  notodo/src/components/calendar/style.js
  notodo/src/components/notodoPage/notodoPage.jsx
  notodo/src/components/notodoPage/style.js
  notodo/src/redux/slice/listSlice.js
  notodo/src/style/globalStyle.js
  notodo/src/style/theme.js
Labels: ☀️ Feature

#21 팔로우 리스트 페이지
  notodo/src/Router.js
  notodo/src/components/Modal/index.jsx
  notodo/src/components/Modal/style.js
  notodo/src/components/TodoPopupMenu/style.js
  notodo/src/components/UserList/UserListComp/index.jsx
  notodo/src/components/UserList/UserListComp/style.js
  notodo/src/components/UserList/index.jsx
  notodo/src/components/UserList/style.js
  notodo/src/pages/FollowListPage/index.jsx
  notodo/src/pages/FollowListPage/style.js
  notodo/src/pages/calendarPage/calendarPage.jsx
  notodo/src/pages/calendarPage/style.js
  notodo/src/pages/loginPage/kakaoLogin.jsx
  notodo/src/pages/loginPage/loginPage.jsx
  notodo/src/pages/loginPage/style.js
  notodo/src/pages/notodoPage/notodoPage.jsx
  notodo/src/pages/notodoPage/style.js
Labels: ☀️ Feature

#22 Feat: Header, NavBar 추가
  notodo/src/Router.js
  notodo/src/components/Header/index.jsx
  notodo/src/components/Header/style.js
  notodo/src/components/NavBar/index.jsx
  notodo/src/components/NavBar/style.js
  notodo/src/components/WeekPicker/style.js
  notodo/src/layouts/MainWrapper/index.jsx
  notodo/src/layouts/MainWrapper/style.js
  notodo/src/pages/FollowListPage/index.jsx
  notodo/src/pages/FollowListPage/style.js
  notodo/src/pages/SearchPage/index.jsx
  notodo/src/pages/SearchPage/style.js
  notodo/src/pages/SettingPage/index.js
  notodo/src/pages/SettingPage/style.js
  notodo/src/pages/calendarPage/style.js
  notodo/src/pages/notodoPage/notodoPage.jsx
  notodo/src/pages/notodoPage/style.js
Labels: ☀️ Feature

#23 Feat: Header, NavBar Fixed 구현
  notodo/src/components/Header/style.js
  notodo/src/components/NavBar/style.js
  notodo/src/pages/SettingPage/index.jsx
  notodo/src/pages/notodoPage/notodoPage.jsx
  notodo/src/pages/notodoPage/style.js
Labels: ☀️ Feature

#24 Feat: 설정 페이지 마크업
  notodo/src/pages/SettingPage/index.jsx
  notodo/src/pages/SettingPage/style.js
Labels: ☀️ Feature

#25 Notodo page
  notodo/src/components/DayState/index.jsx
  notodo/src/components/DayState/style.js
  notodo/src/components/Header/index.jsx
  notodo/src/components/Modal/style.js
  notodo/src/components/NotodoList/index.jsx
  notodo/src/components/NotodoList/style.js
  notodo/src/components/Popup/GuidePopup/index.jsx
  notodo/src/components/Popup/GuidePopup/style.js
  notodo/src/components/Popup/TodoPopup/index.jsx
  notodo/src/components/Popup/TodoPopup/style.js
  notodo/src/pages/notodoPage/notodoPage.jsx
  notodo/src/pages/notodoPage/style.js
Labels: 🐞Bug, ☀️ Feature, 🔨 Refactor, 프론트엔드

#26 Feat: url 공유 기능 추가
  notodo/src/Router.js
  notodo/src/components/Header/index.jsx
  notodo/src/components/Header/style.js
  notodo/src/components/Modal/style.js
  notodo/src/components/NavBar/index.jsx
  notodo/src/components/NavBar/style.js
  notodo/src/pages/SettingPage/index.jsx
  notodo/src/pages/loginPage/kakaoLogin.jsx
  notodo/src/pages/loginPage/loginPage.jsx
Labels: ☀️ Feature, 프론트엔드

#27 친구 관련 기능 구현
  notodo/src/Router.js
  notodo/src/api/api.js
  notodo/src/components/DayState/index.jsx
  notodo/src/components/Header/index.jsx
  notodo/src/components/NotodoList/index.jsx
  notodo/src/components/UserList/index.jsx
  notodo/src/components/calendar/index.jsx
  notodo/src/pages/FollowListPage/index.jsx
Labels: ☀️ Feature

#28 Feat : 친구 검색
  notodo/src/api/api.js
  notodo/src/components/SearchedList/SearchedListComp/index.jsx
  notodo/src/components/SearchedList/SearchedListComp/style.js
  notodo/src/components/SearchedList/index.jsx
  notodo/src/components/SearchedList/style.js
  notodo/src/pages/SearchPage/index.jsx
  notodo/src/pages/SearchPage/style.js
Labels: ☀️ Feature, 프론트엔드

#29 Fix : 친구 검색 API 호출 검색버튼으로 가능하게 하기
  notodo/src/api/api.js
  notodo/src/components/SearchedList/SearchedListComp/index.jsx
  notodo/src/components/SearchedList/index.jsx
  notodo/src/pages/SearchPage/index.jsx
  notodo/src/pages/SearchPage/style.js
Labels: ☀️ Feature, 프론트엔드

#31 기능 구현
  notodo/src/api/api.js
  notodo/src/components/SearchedList/SearchedListComp/index.jsx
  notodo/src/components/SearchedList/SearchedListComp/style.js
  notodo/src/components/SearchedList/index.jsx
  notodo/src/components/SearchedList/style.js
  notodo/src/components/UserInfo/index.jsx
  notodo/src/components/UserList/UserListComp/index.jsx
  notodo/src/components/UserList/index.jsx
  notodo/src/components/UserList/style.js
  notodo/src/components/UserListComp/index.jsx
  notodo/src/components/UserListComp/style.js
  notodo/src/pages/FollowListPage/index.jsx
  notodo/src/pages/FollowListPage/style.js
  notodo/src/pages/SearchPage/index.jsx
  notodo/src/pages/SearchPage/style.js
Labels: ☀️ Feature, 프론트엔드

#33 Fix: 새로고침 에러 수정
  notodo/src/components/Header/index.jsx
  notodo/src/pages/SearchPage/style.js
  notodo/src/redux/store.js
Labels: ☀️ Feature

#34 기능 구현
  notodo/src/api/api.js
  notodo/src/components/UserInfo/index.jsx
  notodo/src/components/UserListComp/index.jsx
  notodo/src/components/calendar/index.jsx
  notodo/src/pages/FollowListPage/index.jsx
  notodo/src/pages/SettingPage/index.jsx
  notodo/src/pages/SettingPage/style.js
  notodo/src/redux/slice/listSlice.js
Labels: ☀️ Feature, 프론트엔드

#36 Feat : 다른 사용자 노토도 페이지에서 캘린더 아이콘 클릭 시, 해당 유저 캘린더 페이지 이동
  notodo/src/api/api.js
  notodo/src/components/Header/index.jsx
  notodo/src/components/UserInfo/index.jsx
  notodo/src/components/UserListComp/style.js
Labels: ☀️ Feature, 프론트엔드

#37 Feat: navBar 종류별 url 아이콘 활성화 구현
  notodo/src/components/NavBar/index.jsx
Labels: ☀️ Feature

#38 Design: 모달 width 수정
  notodo/src/components/Header/index.jsx
  notodo/src/components/Modal/index.jsx
  notodo/src/components/Modal/style.js
  notodo/src/components/NotodoList/index.jsx
Labels: 프론트엔드

#40 Feat : 검색페이지 팔로우 버튼 전환
  notodo/src/components/Header/index.jsx
  notodo/src/components/Header/style.js
  notodo/src/components/SearchedList/SearchedListComp/index.jsx
  notodo/src/components/SearchedList/index.jsx
  notodo/src/components/UserInfo/index.jsx
  notodo/src/pages/SearchPage/index.jsx
Labels: ☀️ Feature, 프론트엔드
